downloadDir: ./data/downloads
tempDir: ./data/temp
dbPath: ./data/database.db
ffmpegPath: ffmpeg
spotify:
  clientID: 
  clientSecret: 
baseURL: http://127.0.0.1
ports:
  downloader: 50999
  genre: 50998
  musicAPI: 50997
endpoints:
  genre: /genre
  meta: /meta
  playlist: /playlist

concurrency:
  download: 5
  conversion: 5
  genre: 4