downloadDir: ./downloads
tempDir: ./temp
dbPath: ./database.db
ffmpegPath: ./../ffmpeg/ffmpeg
spotify:
  clientID: 
  clientSecret: 
baseURL: http://localhost
ports:
  downloader: 50999
  genre: 50998
  musicAPI: 50997
endpoints:
  genre: /genre
  meta: /meta
  playlist: /playlist

concurrency:
  download: 25
  conversion: 5
  genre: 5